misspell_dict = {"aren't" : "are not",
"arent" : "are not",
"can't" : "can not",
"cant" : "can not",
"couldn't" : "could not",
"couldnt" : "could not",
"didn't" : "did not",
"didnt" : "did not",
"doesn't" : "does not",
"doesnt" : "does not",
"don't" : "do not",
"dont" : "do not",
"hadn't" : "had not",
"hadnt" : "had not",
"hasn't" : "has not",
"hasnt" : "has not",
"haven't" : "have not",
"havent" : "have not",
"he'd" : "he would",
"he'll" : "he will",
"he's" : "he is",
"i'd" : "I would",
"id" : "I would",
"i'll" : "I will",
"i'm" : "I am",
"im" : "I am",
"isn't" : "is not",
"isnt" : "is not",
"it's" : "it is",
"it'll":"it will",
"i've" : "I have",
"ive" : "I have",
"let's" : "let us",
"mightn't" : "might not",
"mustn't" : "must not",
"shan't" : "shall not",
"she'd" : "she would",
"shed" : "she would",
"she'll" : "she will",
"she's" : "she is",
"shouldn't" : "should not",
"shouldnt" : "should not",
"that's" : "that is",
"thats" : "that is",
"there's" : "there is",
"theres" : "there is",
"they'd" : "they would",
"theyd" : "they would",
"they'll" : "they will",
"they're" : "they are",
"theyre":  "they are",
"they've" : "they have",
"we'd" : "we would",
"we're" : "we are",
"weren't" : "were not",
"werent" : "were not",
"we've" : "we have",
"what'll" : "what will",
"what're" : "what are",
"what's" : "what is",
"whats" : "what is",
"what've" : "what have",
"where's" : "where is",
"who'd" : "who would",
"whod" : "who would",
"who'll" : "who will",
"who're" : "who are",
"who's" : "who is",
"who've" : "who have",
"won't" : "will not",
"wont" : "will not",
"wouldn't" : "would not",
"wouldnt" : "would not",
"you'd" : "you would",
"you'll" : "you will",
"you're" : "you are",
"you've" : "you have",
"youve" : "you have",
"'re": " are",
"wasn't": "was not",
"we'll":" will",
"u": "you",
"cannot": "can not"}